export const projects = [
 { name:'AI-Powered Customer Support Agent', category:'GENERATIVE AI · RAG · AI AGENTS', date:'Aug — Sep 2026', description:'A knowledge-grounded support agent. Answers with source citations, routes queries, and creates validated support tickets.', problem:'Answer customer questions from a knowledge base and route queries into a support workflow.', built:'A RAG-based assistant with a FastAPI backend, Streamlit chat interface, voice interaction, and a LangGraph workflow for query routing and ticket generation.', stack:['Python','FastAPI','Streamlit','ChromaDB','Ollama','Sentence Transformers','Whisper','LangGraph'], highlights:['Knowledge-base retrieval with source citations','LangGraph query routing and validated support tickets','Voice interaction with Whisper'], pipeline:['User Query','Query Processing','Retriever','Knowledge Base','LLM','Validated Response / Support Ticket'] },
 { name:'Multi-Agent Research System', category:'MULTI-AGENT AI · LLM WORKFLOW', date:'Apr — May 2026', description:'From a research question to a structured report, with specialized agents and a critic in the loop.', problem:'Automate web research, information extraction, and structured report generation.', built:'A coordinated Search, Reader, Writer, and Critic agent system with an interactive Streamlit dashboard for reports, sources, and evaluation.', stack:['Python','LangChain','Streamlit','Ollama','BeautifulSoup'], highlights:['Specialized multi-agent architecture','Web research and information extraction','Critic/evaluation loop and interactive dashboard'], pipeline:['User Research Query','Search Agent','Reader Agent','Writer Agent','Critic Agent','Final Research Report'] },
 { name:'Non-Invasive Anemia Detection', category:'DEEP LEARNING · HEALTHCARE AI', date:'Nov — Dec 2025', description:'Exploring ocular images for anemia detection with transfer learning and ensemble techniques.', problem:'Explore non-invasive anemia detection through deep learning classification of ocular images.', built:'A deep learning system using VGG16, DenseNet121, and InceptionV3, with ensemble techniques and model evaluation.', stack:['Python','TensorFlow','Keras'], highlights:['Transfer learning with three model architectures','Ensemble techniques for classification','Reported evaluation result: 84% accuracy'], pipeline:['Ocular Images','Transfer Learning','VGG16 / DenseNet121 / InceptionV3','Ensemble','Classification & Evaluation'] }
];
export const skills = [
 {name:'AI / Machine Learning',items:['Machine Learning','Deep Learning','NLP','PyTorch','TensorFlow','Keras']},
 {name:'Generative AI',items:['LLMs','RAG','AI Agents','Conversational AI','LangChain','LangGraph','Ollama']},
 {name:'Programming',items:['Python','C++','SQL']},
 {name:'Product Development',items:['FastAPI','Streamlit','ChromaDB','Sentence Transformers','n8n']},
 {name:'Tools & Collaboration',items:['GitHub','VS Code','Jupyter']},
 {name:'Product & Design',items:['Figma','Canva','Excel','User Research','Competitive Analysis']}
];
export const steps = [
 ['Identify the Problem','Start with a real problem, not a model.'],['Understand the User','Learn the needs behind the request.'],['Design the AI Workflow','Map the agents, decisions, and data flow.'],['Build the Model / LLM Pipeline','Choose the intelligence that fits the task.'],['Connect Tools & Data','Bring retrieval, APIs, and context together.'],['Build the Product Interface','Turn the workflow into a usable experience.'],['Evaluate & Iterate','Check outputs and refine the approach.'],['Deploy','Bring the working product to its users.']
];
