import { createFileRoute } from '@tanstack/react-router';
import { useEffect, useState, type FormEvent } from 'react';
import { ArrowUpRight, ArrowRight, ArrowDown, Download, Menu, X, MapPin, BrainCircuit, Code2, Layers3, Workflow, Palette, Wrench, Trophy, GraduationCap, Github, Linkedin, Mail, Phone, FileCheck2 } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Dialog, DialogContent, DialogTitle, DialogDescription, DialogTrigger } from '@/components/ui/dialog';
import { projects, skills, steps } from '@/lib/portfolio-data';
import professionalPhoto from '@/assets/professional_photo.jpeg';
import resume from '@/assets/resume.pdf.asset.json';
import internshipCertificate from '@/assets/internship_certificate.jpeg';

export const Route = createFileRoute('/')({
 head:()=>({meta:[{title:'Portfolio'},{name:'description',content:'Tanishka Gupta is an AI/ML & Generative AI builder in Greater Noida. Explore RAG systems, AI agents, deep learning projects, product research, and design.'},{property:'og:title',content:'Tanishka Gupta — AI/ML & Generative AI Builder'},{property:'og:description',content:'Building intelligent systems that solve real-world problems. AI products, agent workflows, and product-oriented design.'},{property:'og:type',content:'website'},{name:'twitter:card',content:'summary_large_image'}]}),
 component:Portfolio,
});
const nav = ['Home','About','Skills','Projects','Experience','Achievements','Contact'];
const skillIcons=[BrainCircuit,Workflow,Code2,Layers3,Wrench,Palette];
function SectionHeading({number,label,title,description}:{number:string;label:string;title:string;description?:string}){return <div className="section-heading"><div><div className="eyebrow"><span className="section-number">{number}</span>{label}</div><h2>{title}</h2></div>{description&&<p>{description}</p>}</div>}
function ResumeButton(){return <Button asChild size="lg" variant="outline"><a href={resume.url} target="_blank" rel="noreferrer" download="TanishkaGupta_Resume.pdf"><Download/>Download Resume</a></Button>}
function ProjectVisual({index}:{index:number}){return <div className="project-visual" aria-label={index===0?'Customer support architecture':index===1?'Multi-agent research architecture':'84 percent reported model accuracy'}>{index===0?<div className="workflow-preview"><div className="flow-row"><div className="flow-box">User query</div></div><div className="flow-connector"/><div className="flow-row"><div className="flow-box emphasis">LangGraph routing</div></div><div className="flow-connector"/><div className="flow-row"><div className="flow-box">Knowledge base</div><div className="flow-box">Retriever</div></div><div className="flow-connector"/><div className="flow-row"><div className="flow-box emphasis">LLM + context</div></div><div className="flow-connector"/><div className="flow-row"><div className="flow-box">Cited response</div><div className="flow-box">Support ticket</div></div></div>:index===1?<div className="research-flow">{['Search agent','Reader agent','Writer agent','Critic agent'].map(x=><div className="flow-box" key={x}>{x}</div>)}<div className="flow-box emphasis">Research report</div></div>:<div className="metric-visual"><div className="metric-circle"><strong>84<span className="sr-only"> percent</span>%</strong><span>REPORTED ACCURACY</span></div><div className="model-list">VGG16<br/>DenseNet121<br/>InceptionV3<br/>Ensemble learning</div></div>}<div className="visual-caption">{index===0?'RAG SUPPORT WORKFLOW':index===1?'SPECIALIZED AGENTS · CRITIC LOOP':'OCULAR IMAGES → CLASSIFICATION'}</div></div>}
function ProjectCard({project,index}:{project:typeof projects[number];index:number}){return <article className={`project ${index===0?'featured':''}`}><ProjectVisual index={index}/><div className="project-content"><div className="project-meta"><span>{project.category}</span><span>0{index+1}</span></div><h3>{project.name}</h3><p>{project.description}</p><div className="tags">{project.stack.slice(0,index===0?8:5).map(t=><span className="tag" key={t}>{t}</span>)}</div><Dialog><DialogTrigger asChild><Button variant="ghost" className="case-button" aria-label={`Explore ${project.name} case study`}>Explore case study <ArrowUpRight/></Button></DialogTrigger><DialogContent className="case-dialog"><div className="eyebrow">{project.category} · {project.date}</div><DialogTitle>{project.name}</DialogTitle><DialogDescription>{project.description}</DialogDescription><h4>The problem</h4><p>{project.problem}</p><h4>What I built</h4><p>{project.built}</p><h4>Technical architecture</h4><div className="case-pipeline">{project.pipeline.map((s,i)=><span key={s}>{i+1}. {s}</span>)}</div><h4>Technical highlights</h4><ul>{project.highlights.map(h=><li key={h}>{h}</li>)}</ul><h4>Technology stack</h4><div className="tags">{project.stack.map(t=><span className="tag" key={t}>{t}</span>)}</div></DialogContent></Dialog></div></article>}
function Portfolio(){
 const [menu,setMenu]=useState(false);const [compact,setCompact]=useState(false);const [active,setActive]=useState('home');const [draft,setDraft]=useState(false);
 useEffect(()=>{const onScroll=()=>setCompact(window.scrollY>45);onScroll();window.addEventListener('scroll',onScroll,{passive:true});const observer=new IntersectionObserver(entries=>{for(const entry of entries)if(entry.isIntersecting)setActive(entry.target.id)},{rootMargin:'-15% 0px -60% 0px'});document.querySelectorAll('section[id]').forEach(s=>observer.observe(s));return()=>{window.removeEventListener('scroll',onScroll);observer.disconnect()}},[]);
 function sendDraft(event:FormEvent<HTMLFormElement>){event.preventDefault();const data=new FormData(event.currentTarget);const name=String(data.get('name')||'');const email=String(data.get('email')||'');const message=String(data.get('message')||'');window.location.href=`mailto:tg963514@gmail.com?subject=${encodeURIComponent(`Portfolio enquiry from ${name}`)}&body=${encodeURIComponent(`${message}\n\nFrom: ${name}\nEmail: ${email}`)}`;setDraft(true)}
 return <><a className="sr-only focus:not-sr-only" href="#main">Skip to content</a><header className={`navbar ${compact?'compact':''}`}><div className="container nav-inner"><a href="#home" className="logo" aria-label="Tanishka Gupta home">TG<span>.</span></a><nav aria-label="Main navigation" className={`nav-links ${menu?'open':''}`}>{nav.map(n=><a key={n} href={`#${n.toLowerCase()}`} className={active===n.toLowerCase()?'active':''} aria-current={active===n.toLowerCase()?'location':undefined} onClick={()=>setMenu(false)}>{n}</a>)}</nav><a href="#contact" className="nav-contact">Let's talk <ArrowUpRight className="inline size-3"/></a><Button className="mobile-menu" variant="ghost" size="icon" onClick={()=>setMenu(!menu)} aria-label={menu?'Close navigation':'Open navigation'} aria-expanded={menu}>{menu?<X/>:<Menu/>}</Button></div></header>
 <main id="main"><section id="home" className="hero"><div className="container"><div className="hero-grid"><div><div className="eyebrow">AI/ML · GENERATIVE AI · AI AGENTS</div><h1>Building AI systems<br/>that solve <span>real-world<br className="hidden md:block"/> problems.</span></h1><p className="intro"><span className="hero-name">I'm Tanishka Gupta.</span> A Computer Science student focused on AI/ML and Generative AI. I build end-to-end AI products using LLMs, RAG, AI agents and deep learning.</p><div className="hero-actions"><Button asChild size="lg"><a href="#projects">View My Work <ArrowUpRight/></a></Button><ResumeButton/></div><a href="#contact" className="connect-link">Let's Connect <ArrowRight className="size-4"/></a></div><div className="portrait-scene"><span className="scene-label">INTELLIGENCE × PRODUCT × DESIGN</span><img className="portrait" src={professionalPhoto} alt="Professional portrait of Tanishka Gupta" width="768" height="1025" fetchPriority="high"/><span className="scene-node" aria-hidden="true"><BrainCircuit className="size-18 size-5"/></span><div className="photo-tag"><span className="status-dot"/>AI/ML & Generative AI Builder</div></div></div><div className="hero-bottom"><span><MapPin className="size-3"/>GREATER NOIDA, INDIA</span><span>AI SYSTEMS. THOUGHTFUL PRODUCTS. PURPOSEFUL DESIGN.</span><a href="#about" className="flex items-center gap-2">SCROLL TO EXPLORE <ArrowDown className="size-3"/></a></div></div></section>
 <section id="about" className="section"><div className="container"><SectionHeading number="01" label="A little about me" title="Beyond the Models."/><div className="about-grid"><div><p className="about-copy">For me, the interesting part isn't just training a model. It's taking a problem and turning it into <strong>something people can actually use.</strong><br/><br/>I bring together AI/ML, deep learning, and Generative AI—from LLM applications and RAG to AI agents—with <strong>product thinking and an eye for design.</strong></p><div className="story">Problem <ArrowRight className="size-3"/> Intelligence <ArrowRight className="size-3"/> Product <ArrowRight className="size-3"/> Impact</div></div><div className="learning">{[['Learn','Build a strong AI/ML foundation.'],['Build','Turn ideas into working products.'],['Experiment','Explore models, agents, and workflows.'],['Deploy','Connect intelligence to an interface.']].map(([t,d],i)=><div className="learning-item" key={t}><span>0{i+1}</span><h3>{t}</h3><p>{d}</p></div>)}</div></div></div></section>
 <section id="skills" className="section"><div className="container"><SectionHeading number="02" label="My toolkit" title="The tools behind the thinking." description="From model development to the final interface. A toolkit for building the whole product."/><div className="skills-grid">{skills.map((s,i)=>{const Icon=skillIcons[i];return <article className="skill-card" key={s.name}><div className="skill-top"><h3>{s.name}</h3>{Icon&&<Icon aria-hidden="true"/>}</div><div className="tags">{s.items.map(t=><span className="tag" key={t}>{t}</span>)}</div></article>})}</div></div></section>
 <section id="projects" className="section"><div className="container"><SectionHeading number="03" label="Selected work" title="Ideas, built into intelligence." description="Practical AI systems with a clear problem, a considered architecture, and a working product."/><div className="projects-grid">{projects.map((p,i)=><ProjectCard project={p} index={i} key={p.name}/>)}</div><a className="text-link mt-7" href="https://github.com/Tanishka798" target="_blank" rel="noreferrer"><Github className="size-4"/>Explore my GitHub <ArrowUpRight className="size-3"/></a></div></section>
 <section className="section" id="workflow"><div className="container"><SectionHeading number="04" label="The process" title="How I Build AI Products" description="Good AI products take more than a prompt. Here’s how I approach the journey from problem to product."/><div className="build-grid">{steps.map(([t,d],i)=><article className="build-step" key={t}><span>0{i+1} <ArrowRight className="inline ml-2 size-3"/></span><h3>{t}</h3><p>{d}</p></article>)}</div></div></section>
 <section id="experience" className="section"><div className="container"><SectionHeading number="05" label="Real-world experience" title="Where technology meets people."/><div className="experience-grid"><div className="experience-date">JUNE 2026 — AUGUST 2026<br/><span className="inline-block mt-3">REMOTE INTERNSHIP</span></div><div className="experience-content"><h3>Product R&D Intern</h3><p className="muted text-sm">Cups Innovative Educations Pvt. Ltd.</p><ul><li>Conducted user surveys for an ed-tech platform and translated feedback into product improvement suggestions.</li><li>Benchmarked content, design, and assessments against competitors.</li><li>Identified 3+ concrete improvement areas for the team.</li></ul><div className="tags mb-5">{['User Research','Product Thinking','Technology'].map(t=><span className="tag" key={t}>{t}</span>)}</div><div className="flex flex-wrap gap-5"><a href={internshipCertificate} target="_blank" rel="noreferrer" className="text-link"><FileCheck2 className="size-4"/>View internship certificate <ArrowUpRight className="size-3"/></a></div></div></div></div></section>
 <section id="achievements" className="section"><div className="container"><SectionHeading number="06" label="Milestones" title="Recognition along the way."/><div className="achievements-grid"><article className="achievement"><Trophy/><h3>Runner-up</h3><h4>Ops Tree Hackathon</h4><p>Led ideation and product framing under time constraints.</p></article><article className="achievement"><Trophy/><h3>Top 50</h3><h4>Smart India Hackathon</h4><p>Selected among 2,400+ teams in a national-scale competition.</p></article><article className="achievement"><GraduationCap/><h3>Academic Scholarship</h3><h4>First year of B.Tech</h4><p>Awarded an academic scholarship during my first year.</p></article></div><div className="certificate-row"><div><div className="eyebrow mb-2">Design, too.</div><h3>Graphic Design Essentials — Canva</h3><p>Certificate of completion · August 11, 2026 · Credential 266afd</p></div></div></div></section>
 <section className="section" id="education"><div className="container"><SectionHeading number="07" label="The foundation" title="Learning with purpose."/><div className="education"><div><h3>B.Tech — Computer Science Engineering (AI/ML)</h3><p>Sharda University · Greater Noida, India<br/>2023 — Present</p></div><div className="cgpa">8.6<span>CGPA</span></div></div></div></section>
 <section className="resume-band"><div className="container resume-inner"><div><h2>Want to know more about my work?</h2><p>Explore my experience, technical skills and projects in detail.</p></div><ResumeButton/></div></section>
 <section id="contact" className="section"><div className="container"><div className="contact-grid"><div className="contact-copy"><SectionHeading number="08" label="Let's connect" title="Let's Build Something Intelligent."/><p>I'm open to opportunities, collaborations, interesting AI problems and conversations around Generative AI.</p><div className="contact-links"><a href="mailto:tg963514@gmail.com"><Mail/>tg963514@gmail.com <ArrowUpRight/></a><a href="https://www.linkedin.com/in/tanishka-gupta-6213892a7/?isSelfProfile=true" target="_blank" rel="noreferrer"><Linkedin/>LinkedIn <ArrowUpRight/></a><a href="https://github.com/Tanishka798" target="_blank" rel="noreferrer"><Github/>GitHub <ArrowUpRight/></a><a href="tel:+919522100624"><Phone/>+91 95221 00624</a></div></div><form className="contact-form" onSubmit={sendDraft}><div className="form-row"><label>Name<input name="name" autoComplete="name" required maxLength={100}/></label><label>Email<input type="email" name="email" autoComplete="email" required maxLength={254}/></label></div><label>Message<textarea name="message" required maxLength={4000}/></label><Button type="submit" size="lg">Send Message <ArrowUpRight/></Button><p className="form-note" role="status">{draft?'Your email draft has been requested. Send it from your email app; nothing has been sent by this website.':'Opens a draft in your email app. Messages are not sent by this website.'}</p></form></div></div></section>
 </main><footer className="footer"><div className="container footer-inner"><a className="logo" href="#home">TG<span>.</span></a><span>© 2026 Tanishka Gupta</span><span>Intelligence with intention.</span><a href="#home" className="flex items-center gap-2">Back to top <ArrowUpRight className="size-3"/></a></div></footer></>
}
